AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  CanaryTestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  CanaryTestApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: canary_test_api/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        CanaryTestApiGateway:
          Type: Api
          Properties:
            Path: /canary
            Method: get
            RestApiId: !Ref CanaryTestApiGateway

  CanaryTestGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  CanaryTestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: canary_test/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_ENDPOINT: !Sub "https://${CanaryTestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/canary/"
      Events:
        CanaryTestGateway:
          Type: Api
          Properties:
            Path: /canary
            Method: get
            RestApiId: !Ref CanaryTestGateway

Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
  CanaryTestApiGateway:
    Description: API Gateway endpoint URL for Prod stage for Canary Test API
    Value: !Sub "https://${CanaryTestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CanaryTestGateway:
    Description: API Gateway endpoint URL for Prod stage for Canary Test function
    Value: !Sub "https://${CanaryTestGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CanaryTestFunction:
    Description: Canary Test Lambda Function ARN
    Value: !GetAtt CanaryTestFunction.Arn
  CanaryTestApiFunction:
    Description: Canary Test Api Lambda Function ARN
    Value: !GetAtt CanaryTestApiFunction.Arn
  CanaryTestFunctionIamRole:
    Description: Implicit IAM Role created for Canary Test function
    Value: !GetAtt CanaryTestFunctionRole.Arn
